### ISSUE TITLE
Where can one find the data that you use to create the webapp?

### ISSUE THREAD

**Issue by LinguList** [evolaemp/northeuralex_website#3]
I looked for it, but could not find the repository? I'd be interested in a list of source/language, so we can properly convert the data to CLDF (see [here](https://github.com/lexibank/northeuralex).

**Comment by pavelsof** [comment]
I happen to still have the files that were used to initialise the database back in 2017 (and which I believe is still the current online database). However, given that I am out of the loop by now and that I do not remember why these files have not been included in the repo in the first place, I would first ask @jdellert before sharing them.

**Comment by jdellert** [comment]
We are in the process of exporting NorthEuraLex 0.91 (a bugfix release without any new languages) to an official CLDF version ourselves, which will include some updates to lexical choices, transcriptions, language data, concept definitions, and especially the sources. The information in the current web interface, which is indeed still identical to what we released in 2017, is therefore already outdated in some respects. We expect to redeploy the new version towards the end of this year, and would be willing to share the most recent versions of all the relevant files then. However, we would prefer to be the ones maintaining the official CLDF version from now on, given our previous experience with the unfortunately somewhat suboptimal (though of course useful) Zenodo release.

**Comment by LinguList** [comment]
Excellent, you can see from @Anaphory, how this can be done, with help of the lexibank software. For us it is even better, as we don't have to maintain stuff.

**Comment by jdellert** [comment]
I agree! If database projects have the manpower to maintain and update their own version (and we currently do), I think it makes sense to decentralize the efforts in this way. Regarding the software, we will be rolling out our own deployment infrastructure due to the many automated transformation steps between the formats in which we collect our data and the release version. However, our gial is full compatibility with Lexibank, and will be happy to contribute to resolving any issues detracting from that compatibility which you might stumble upon in our next release version.

**Comment by LinguList** [comment]
Just have a look at pylexibank and pycldf, if you use Python, as it will probably make it easier to see how things work, with standard implementations of the w3 spec of csvw, etc. Good progress with everything!
